### ISSUE TITLE
[Feature] 채팅방 기능 구현하기

### ISSUE THREAD

**Issue by ImWonYong** [f-lab-edu/Raim#22]
# Issue: 채팅방 기능 구현

## Description
채팅방 CRUD 구현

## Todo
- [x] 채팅룸 만들기
  - [x] 개인 채팅방 만들기
  - [x] 그룹 채팅방 만들기(중복 검사하지 않고 방 생성)
- [x] 채팅룸 DTO
  - [x] 채팅룸 생성을 위한 request dto
  - [x] 채팅룸 응답을 위한 response dto
- [x] 채팅룸 확인하기
  - [x] 개인 채팅방이 이미 존재하는지 확인하기
- [ ] 채팅룸에 친구 초대하기
  - [x] 개인 채팅 방에서 초대 시 단체 채팅방으로 새로운 방 생성하기
  - [x] 단체 채팅 방에서 초대 시 단체 채팅방으로 초대하기
    - [ ] 초대 목록에 유저가 이미 단체 채팅방에 멤버인지 확인하기
- [ ] 채팅룸 삭제하기
  - [ ] 개인 채팅방에 두 유저가 모두 나간 경우?? (과연 삭제하는가?)
  - [ ] 단체 채팅방에 모든 유저가 나간 경우
- [x] 채팅룸 가져오기
  - [x] 기본 페이지네이션

**Comment by ImWonYong** [comment]
1. 채팅방 조회 시 N+1 문제 등이 발생하지 않는지 확인하고 처리하기
2. 일반 페이지네이션에 대한 성능 테스트를 해보고 더 좋은 방식으로 개선해보기
