### ISSUE TITLE
[Improvement] 채팅방 기능 개선

### ISSUE THREAD

**Issue by ImWonYong** [f-lab-edu/Raim#27]
# Issue: 기존 채팅방 기능 개선

## Description
채팅방 기능을 조금 더 개선합니다.

## Todo
- [ ] 채팅방 인원 제한
    - [ ] 채팅방 생성 시 제한 인원 확인
    - [ ] 채팅방 초대 시 제한 인원 확인
- [ ] 초대 시 이미 채팅방에 존재하는 사람인지 확인하기
